Updated Django Rest Framework and Serializer - Tests Still Failing
Resolved errors caused by using outdated version of djangorestframework.

This unfortunately caused actual failures in the tests now.

The initial error was:
AssertionError: Relational field must provide a `queryset` argument, or set read_only=`True')

This was fixed by adding read_only=`True' to several lines in serializer.py.

However, this resulted in a new error:
AttributeError: 'ManyToOneRel' object has no attribute 'unique_for_date'

This suggests a continued problem in serializer.py in processing the url for
that client.get call, but I am currently stumped as to where that might be occurring.